---
- name: Write a vault secret
  hosts: all
  tasks:

  - name: "Getting a token from {{ vault_address }}"
    uri:
      method: POST
      body:
        password: "{{ password }}"
      body_format: "json"
      url: "{{ vault_proto }}://{{ vault_address }}/v1/auth/{{ vault_method }}/login/{{ username }}"
      status_code:
        - 200
        - 204
    register: vault_token
    no_log: yes
    when: vault_token is not defined

  - set_fact:
      vault_token_generated: "{{ vault_token is not string }}"
    no_log: yes
    
  - set_fact:
      vault_token: "{{ vault_token.json.auth.client_token }}"
    no_log: yes
    when: vault_token is not string
    
  - name: "Render template using vault secret"
    vars:
      db_password: >-
        {{ (lookup('community.hashi_vault.hashi_vault', vault_path + '/password:password',
        auth_method='token', token=vault_token, validate_certs=False,
        url='{}://{}'.format(vault_proto, vault_address))) }}
      db_username: >-
        {{ (lookup('community.hashi_vault.hashi_vault', vault_path + '/data:username',
        auth_method='token', token=vault_token, validate_certs=False,
        url='{}://{}'.format(vault_proto, vault_address))) }}
      db_url: >-
        {{ (lookup('community.hashi_vault.hashi_vault', vault_path + '/data:url',
        auth_method='token', token=vault_token, validate_certs=False,
        url='{}://{}'.format(vault_proto, vault_address))) }}
    template:
      dest: /tmp/rendered.txt
      src: example.tpl

  - name: "Reovking token"
    uri:
      method: POST
      body:
        token: "{{ vault_token }}"
      body_format: "json"
      headers:
        Authorization: "Bearer {{ vault_token }}"
      url: "{{ vault_proto }}://{{ vault_address }}/v1/auth/token/revoke"
      status_code:
        - 200
        - 204
    no_log: yes
    when: vault_token_generated
